name: Build and Release Extension

# Trigger the workflow when a tag starting with 'v' is pushed (e.g., v1.1.0)
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run build

      - name: Create ZIP
        run: zip -r frost2x-${{ github.ref_name }}.zip dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: frost2x-${{ github.ref_name }}.zip
          draft: true      # Set to true if you want drafts.
          prerelease: true # Set to true for beta releases.